"""Localization of competition geography for English-speaking users.

cubingrf.org renders city names only in Russian, so the bot transliterates
them for its English UI. A curated map covers the most common Russian cities
with their conventional English spellings (Moscow, Saint Petersburg, Kazan,
...); everything else falls back to standard Cyrillic-to-Latin
transliteration (GOST 7.79-2000 System B) with the common "ый"/"ий" ->
"y" word endings.
"""
import re
from typing import Dict

# Russian city -> conventional English name. Keys are lower-cased.
CITY_NAMES: Dict[str, str] = {
    "москва": "Moscow",
    "санкт-петербург": "Saint Petersburg",
    "спб": "Saint Petersburg",
    "новосибирск": "Novosibirsk",
    "екатеринбург": "Yekaterinburg",
    "нижний новгород": "Nizhny Novgorod",
    "казань": "Kazan",
    "челябинск": "Chelyabinsk",
    "омск": "Omsk",
    "самара": "Samara",
    "ростов-на-дону": "Rostov-on-Don",
    "уфа": "Ufa",
    "красноярск": "Krasnoyarsk",
    "воронеж": "Voronezh",
    "пермь": "Perm",
    "волгоград": "Volgograd",
    "краснодар": "Krasnodar",
    "саратов": "Saratov",
    "тюмень": "Tyumen",
    "тольятти": "Tolyatti",
    "ижевск": "Izhevsk",
    "барнаул": "Barnaul",
    "ульяновск": "Ulyanovsk",
    "иркутск": "Irkutsk",
    "хабаровск": "Khabarovsk",
    "владивосток": "Vladivostok",
    "ярославль": "Yaroslavl",
    "махачкала": "Makhachkala",
    "томск": "Tomsk",
    "оренбург": "Orenburg",
    "кемерово": "Kemerovo",
    "новокузнецк": "Novokuznetsk",
    "рязань": "Ryazan",
    "астрахань": "Astrakhan",
    "набережные челны": "Naberezhnye Chelny",
    "пенза": "Penza",
    "липецк": "Lipetsk",
    "киров": "Kirov",
    "чебоксары": "Cheboksary",
    "тула": "Tula",
    "калининград": "Kaliningrad",
    "балашиха": "Balashikha",
    "курск": "Kursk",
    "севастополь": "Sevastopol",
    "сочи": "Sochi",
    "ставрополь": "Stavropol",
    "улан-удэ": "Ulan-Ude",
    "тверь": "Tver",
    "магнитогорск": "Magnitogorsk",
    "подольск": "Podolsk",
    "калуга": "Kaluga",
    "химки": "Khimki",
    "мурманск": "Murmansk",
    "петрозаводск": "Petrozavodsk",
    "смоленск": "Smolensk",
    "белгород": "Belgorod",
    "владимир": "Vladimir",
    "архангельск": "Arkhangelsk",
    "вологда": "Vologda",
    "череповец": "Cherepovets",
    "сыктывкар": "Syktyvkar",
    "великий новгород": "Veliky Novgorod",
    "псков": "Pskov",
    "грозный": "Grozny",
    "владикавказ": "Vladikavkaz",
    "нальчик": "Nalchik",
    "майкоп": "Maykop",
    "элиста": "Elista",
    "анапа": "Anapa",
    "геленджик": "Gelendzhik",
    "дербент": "Derbent",
    "каспийск": "Kaspiysk",
    "кисловодск": "Kislovodsk",
    "пятигорск": "Pyatigorsk",
    "ессентуки": "Yessentuki",
    "йошкар-ола": "Yoshkar-Ola",
    "тамбов": "Tambov",
    "брянск": "Bryansk",
    "орёл": "Oryol",
    "саранск": "Saransk",
    "симферополь": "Simferopol",
    "якутск": "Yakutsk",
    "чита": "Chita",
    "благовещенск": "Blagoveshchensk",
    "сургут": "Surgut",
    "нижневартовск": "Nizhnevartovsk",
    "королёв": "Korolyov",
    "мытищи": "Mytishchi",
    "люберцы": "Lyubertsy",
    "одинцово": "Odintsovo",
    "долгопрудный": "Dolgoprudny",
    "дмитров": "Dmitrov",
    "сергиев посад": "Sergiev Posad",
    "коломна": "Kolomna",
    "кашира": "Kashira",
    "зеленоград": "Zelenograd",
    "троицк": "Troitsk",
    "щёлково": "Shchyolkovo",
    "жуковский": "Zhukovsky",
    "раменское": "Ramenskoye",
    "воскресенск": "Voskresensk",
    "клин": "Klin",
    "серпухов": "Serpukhov",
    "орехово-зуево": "Orekhovo-Zuyevo",
    "наро-фоминск": "Naro-Fominsk",
    "обнинск": "Obninsk",
    "пущино": "Pushchino",
    "фрязино": "Fryazino",
    "черноголовка": "Chernogolovka",
    "дубна": "Dubna",
    "ступино": "Stupino",
    "миасс": "Miass",
    "златоуст": "Zlatoust",
    "чебаркуль": "Chebarkul",
    "каменск-уральский": "Kamensk-Uralsky",
    "нижний тагил": "Nizhny Tagil",
    "серов": "Serov",
    "альметьевск": "Almetyevsk",
    "нижнекамск": "Nizhnekamsk",
    "зеленодольск": "Zelenodolsk",
    "салават": "Salavat",
    "стерлитамак": "Sterlitamak",
    "нефтекамск": "Neftekamsk",
    "октябрьский": "Oktyabrsky",
    "орск": "Orsk",
    "новотроицк": "Novotroitsk",
    "бийск": "Biysk",
    "рубцовск": "Rubtsovsk",
    "горно-алтайск": "Gorno-Altaysk",
    "абакан": "Abakan",
    "кызыл": "Kyzyl",
    "черкесск": "Cherkessk",
    "ханты-мансийск": "Khanty-Mansiysk",
    "тобольск": "Tobolsk",
    "ноябрьск": "Noyabrsk",
    "новый уренгой": "Novy Urengoy",
    "салехард": "Salekhard",
    "усть-илимск": "Ust-Ilimsk",
    "ангарск": "Angarsk",
    "братск": "Bratsk",
    "уссурийск": "Ussuriysk",
    "находка": "Nakhodka",
    "артём": "Artyom",
    "комсомольск-на-амуре": "Komsomolsk-on-Amur",
    "южно-сахалинск": "Yuzhno-Sakhalinsk",
    "петропавловск-камчатский": "Petropavlovsk-Kamchatsky",
    "мирный": "Mirny",
    "нерюнгри": "Neryungri",
    "воркута": "Vorkuta",
    "ухта": "Ukhta",
    "северодвинск": "Severodvinsk",
    "котлас": "Kotlas",
    "рыбинск": "Rybinsk",
    "кострома": "Kostroma",
    "иваново": "Ivanovo",
    "суздаль": "Suzdal",
    "муром": "Murom",
    "торжок": "Torzhok",
    "ржев": "Rzhev",
    "вязьма": "Vyazma",
    "новомосковск": "Novomoskovsk",
    "елец": "Yelets",
    "мичуринск": "Michurinsk",
    "энгельс": "Engels",
    "балаково": "Balakovo",
    "волжский": "Volzhsky",
    "камышин": "Kamyshin",
    "адлер": "Adler",
    "армавир": "Armavir",
    "новороссийск": "Novorossiysk",
    "туапсе": "Tuapse",
    "таганрог": "Taganrog",
    "шахты": "Shakhty",
    "новочеркасск": "Novocherkassk",
    "волгодонск": "Volgodonsk",
    "азов": "Azov",
    "невинномысск": "Nevinnomyssk",
    "минеральные воды": "Mineralnye Vody",
    "сызрань": "Syzran",
    "димитровград": "Dimitrovgrad",
    "елабуга": "Yelabuga",
    "первоуральск": "Pervouralsk",
    "краснотурьинск": "Krasnoturinsk",
    "курган": "Kurgan",
    "ишим": "Ishim",
    "тара": "Tara",
    "бердск": "Berdsk",
    "искитим": "Iskitim",
    "прокопьевск": "Prokopyevsk",
    "белово": "Belovo",
    "ленинск-кузнецкий": "Leninsk-Kuznetsky",
    "междуреченск": "Mezhdurechensk",
    "ачинск": "Achinsk",
    "канск": "Kansk",
    "минусинск": "Minusinsk",
    "железногорск": "Zheleznogorsk",
    "зеленогорск": "Zelenogorsk",
    "лесосибирск": "Lesosibirsk",
    "норильск": "Norilsk",
    "биробиджан": "Birobidzhan",
    "магадан": "Magadan",
    "черняховск": "Chernyakhovsk",
    "советск": "Sovetsk",
    "светлогорск": "Svetlogorsk",
    "зеленоградск": "Zelenogradsk",
    "ялта": "Yalta",
    "алушта": "Alushta",
    "евпатория": "Yevpatoria",
    "феодосия": "Feodosia",
    "керчь": "Kerch",
    "саки": "Saki",
    "джанкой": "Dzhankoy",
    "бахчисарай": "Bakhchisaray",
    "мисайлово": "Misailovo",
}

# GOST 7.79-2000 System B letter mapping.
_TRANSLIT = str.maketrans({
    "а": "a", "б": "b", "в": "v", "г": "g", "д": "d", "е": "e", "ё": "e",
    "ж": "zh", "з": "z", "и": "i", "й": "y", "к": "k", "л": "l", "м": "m",
    "н": "n", "о": "o", "п": "p", "р": "r", "с": "s", "т": "t", "у": "u",
    "ф": "f", "х": "kh", "ц": "ts", "ч": "ch", "ш": "sh", "щ": "shch",
    "ъ": "", "ы": "y", "ь": "", "э": "e", "ю": "yu", "я": "ya",
    "А": "A", "Б": "B", "В": "V", "Г": "G", "Д": "D", "Е": "E", "Ё": "E",
    "Ж": "Zh", "З": "Z", "И": "I", "Й": "Y", "К": "K", "Л": "L", "М": "M",
    "Н": "N", "О": "O", "П": "P", "Р": "R", "С": "S", "Т": "T", "У": "U",
    "Ф": "F", "Х": "Kh", "Ц": "Ts", "Ч": "Ch", "Ш": "Sh", "Щ": "Shch",
    "Ъ": "", "Ы": "Y", "Ь": "", "Э": "E", "Ю": "Yu", "Я": "Ya",
})

# Conventional word endings (applied to the Latin output): "Новый" -> "Novy",
# "Нижний" -> "Nizhny" ("ый"/"ий" transliterate to "yy"/"iy" at word ends).
_WORD_ENDING_RE = re.compile(r"(?:yy|iy)(?=[\s\-]|$)")


def transliterate(text: str) -> str:
    """Transliterate Russian text to Latin (GOST 7.79-2000 System B).

    Non-Cyrillic characters (hyphens, Latin letters, digits) pass through
    unchanged.
    """
    out = text.translate(_TRANSLIT)
    return _WORD_ENDING_RE.sub("y", out)


def localize_city(city: str, language: str = "ru") -> str:
    """The city name in the requested language.

    Russian (and unknown languages) keep the original city. For English the
    conventional English spelling is used when known, otherwise a
    transliteration of the Russian name.
    """
    if language != "en" or not city:
        return city
    key = city.strip().lower()
    if key in CITY_NAMES:
        return CITY_NAMES[key]
    return transliterate(city)